name: FreeBuild-Explo
version: 2.0
author: TheTimeDev_
api-version: 1.13
main: fr.thetimedev.freebuild.Main
commands:
  spawn:
    description: Commande de spawn
  menu:
    description: Commande de test
  setspawn:
    description: Commande pour set la position du spawn
  freebuild-reload:
    description: Commande de reload de la config